// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: APSdet_GPB.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "APSdet_GPB.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace APSdet_GPB {

namespace {

const ::google::protobuf::Descriptor* AGP_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AGP_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* AGP_ArrayDataType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_APSdet_5fGPB_2eproto() {
  protobuf_AddDesc_APSdet_5fGPB_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "APSdet_GPB.proto");
  GOOGLE_CHECK(file != NULL);
  AGP_descriptor_ = file->message_type(0);
  static const int AGP_offsets_[10] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, numdimdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, dimdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, datatype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, valuesdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, unquieid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, numattrs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, nameattrs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, typeattrs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, valuesattrs_),
  };
  AGP_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      AGP_descriptor_,
      AGP::default_instance_,
      AGP_offsets_,
      -1,
      -1,
      -1,
      sizeof(AGP),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AGP, _is_default_instance_));
  AGP_ArrayDataType_descriptor_ = AGP_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_APSdet_5fGPB_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      AGP_descriptor_, &AGP::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_APSdet_5fGPB_2eproto() {
  delete AGP::default_instance_;
  delete AGP_reflection_;
}

void protobuf_AddDesc_APSdet_5fGPB_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020APSdet_GPB.proto\022\nAPSdet_GPB\"\332\002\n\003AGP\022\022"
    "\n\nnumDimData\030\001 \001(\005\022\017\n\007dimData\030\002 \001(\t\022/\n\010d"
    "ataType\030\003 \001(\0162\035.APSdet_GPB.AGP.ArrayData"
    "Type\022\022\n\nvaluesData\030\004 \001(\014\022\020\n\010unquieID\030\005 \001"
    "(\005\022\021\n\ttimeStamp\030\006 \001(\001\022\020\n\010numAttrs\030\007 \001(\005\022"
    "\021\n\tnameAttrs\030\010 \001(\t\022\021\n\ttypeAttrs\030\t \001(\t\022\023\n"
    "\013valuesAttrs\030\n \001(\014\"w\n\rArrayDataType\022\t\n\005U"
    "INT8\020\000\022\010\n\004INT8\020\001\022\n\n\006UINT16\020\002\022\t\n\005INT16\020\003\022"
    "\n\n\006UINT32\020\004\022\t\n\005INT32\020\005\022\t\n\005INT64\020\006\022\013\n\007FLO"
    "AT32\020\007\022\013\n\007FLOAT64\020\010b\006proto3", 387);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "APSdet_GPB.proto", &protobuf_RegisterTypes);
  AGP::default_instance_ = new AGP();
  AGP::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_APSdet_5fGPB_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_APSdet_5fGPB_2eproto {
  StaticDescriptorInitializer_APSdet_5fGPB_2eproto() {
    protobuf_AddDesc_APSdet_5fGPB_2eproto();
  }
} static_descriptor_initializer_APSdet_5fGPB_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

const ::google::protobuf::EnumDescriptor* AGP_ArrayDataType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AGP_ArrayDataType_descriptor_;
}
bool AGP_ArrayDataType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const AGP_ArrayDataType AGP::UINT8;
const AGP_ArrayDataType AGP::INT8;
const AGP_ArrayDataType AGP::UINT16;
const AGP_ArrayDataType AGP::INT16;
const AGP_ArrayDataType AGP::UINT32;
const AGP_ArrayDataType AGP::INT32;
const AGP_ArrayDataType AGP::INT64;
const AGP_ArrayDataType AGP::FLOAT32;
const AGP_ArrayDataType AGP::FLOAT64;
const AGP_ArrayDataType AGP::ArrayDataType_MIN;
const AGP_ArrayDataType AGP::ArrayDataType_MAX;
const int AGP::ArrayDataType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int AGP::kNumDimDataFieldNumber;
const int AGP::kDimDataFieldNumber;
const int AGP::kDataTypeFieldNumber;
const int AGP::kValuesDataFieldNumber;
const int AGP::kUnquieIDFieldNumber;
const int AGP::kTimeStampFieldNumber;
const int AGP::kNumAttrsFieldNumber;
const int AGP::kNameAttrsFieldNumber;
const int AGP::kTypeAttrsFieldNumber;
const int AGP::kValuesAttrsFieldNumber;
#endif  // !_MSC_VER

AGP::AGP()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:APSdet_GPB.AGP)
}

void AGP::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

AGP::AGP(const AGP& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:APSdet_GPB.AGP)
}

void AGP::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  numdimdata_ = 0;
  dimdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  datatype_ = 0;
  valuesdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  unquieid_ = 0;
  timestamp_ = 0;
  numattrs_ = 0;
  nameattrs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  typeattrs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesattrs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

AGP::~AGP() {
  // @@protoc_insertion_point(destructor:APSdet_GPB.AGP)
  SharedDtor();
}

void AGP::SharedDtor() {
  dimdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nameattrs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  typeattrs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesattrs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void AGP::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AGP::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AGP_descriptor_;
}

const AGP& AGP::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_APSdet_5fGPB_2eproto();
  return *default_instance_;
}

AGP* AGP::default_instance_ = NULL;

AGP* AGP::New(::google::protobuf::Arena* arena) const {
  AGP* n = new AGP;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AGP::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<AGP*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(numdimdata_, datatype_);
  ZR_(timestamp_, numattrs_);
  dimdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nameattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  typeattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool AGP::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:APSdet_GPB.AGP)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 numDimData = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numdimdata_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_dimData;
        break;
      }

      // optional string dimData = 2;
      case 2: {
        if (tag == 18) {
         parse_dimData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dimdata()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->dimdata().data(), this->dimdata().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "APSdet_GPB.AGP.dimData"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_dataType;
        break;
      }

      // optional .APSdet_GPB.AGP.ArrayDataType dataType = 3;
      case 3: {
        if (tag == 24) {
         parse_dataType:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_datatype(static_cast< ::APSdet_GPB::AGP_ArrayDataType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_valuesData;
        break;
      }

      // optional bytes valuesData = 4;
      case 4: {
        if (tag == 34) {
         parse_valuesData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_valuesdata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_unquieID;
        break;
      }

      // optional int32 unquieID = 5;
      case 5: {
        if (tag == 40) {
         parse_unquieID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &unquieid_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_timeStamp;
        break;
      }

      // optional double timeStamp = 6;
      case 6: {
        if (tag == 49) {
         parse_timeStamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &timestamp_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_numAttrs;
        break;
      }

      // optional int32 numAttrs = 7;
      case 7: {
        if (tag == 56) {
         parse_numAttrs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numattrs_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_nameAttrs;
        break;
      }

      // optional string nameAttrs = 8;
      case 8: {
        if (tag == 66) {
         parse_nameAttrs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nameattrs()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nameattrs().data(), this->nameattrs().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "APSdet_GPB.AGP.nameAttrs"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_typeAttrs;
        break;
      }

      // optional string typeAttrs = 9;
      case 9: {
        if (tag == 74) {
         parse_typeAttrs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_typeattrs()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->typeattrs().data(), this->typeattrs().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "APSdet_GPB.AGP.typeAttrs"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_valuesAttrs;
        break;
      }

      // optional bytes valuesAttrs = 10;
      case 10: {
        if (tag == 82) {
         parse_valuesAttrs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_valuesattrs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:APSdet_GPB.AGP)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:APSdet_GPB.AGP)
  return false;
#undef DO_
}

void AGP::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:APSdet_GPB.AGP)
  // optional int32 numDimData = 1;
  if (this->numdimdata() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->numdimdata(), output);
  }

  // optional string dimData = 2;
  if (this->dimdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dimdata().data(), this->dimdata().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "APSdet_GPB.AGP.dimData");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->dimdata(), output);
  }

  // optional .APSdet_GPB.AGP.ArrayDataType dataType = 3;
  if (this->datatype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->datatype(), output);
  }

  // optional bytes valuesData = 4;
  if (this->valuesdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->valuesdata(), output);
  }

  // optional int32 unquieID = 5;
  if (this->unquieid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->unquieid(), output);
  }

  // optional double timeStamp = 6;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->timestamp(), output);
  }

  // optional int32 numAttrs = 7;
  if (this->numattrs() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->numattrs(), output);
  }

  // optional string nameAttrs = 8;
  if (this->nameattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nameattrs().data(), this->nameattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "APSdet_GPB.AGP.nameAttrs");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->nameattrs(), output);
  }

  // optional string typeAttrs = 9;
  if (this->typeattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->typeattrs().data(), this->typeattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "APSdet_GPB.AGP.typeAttrs");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->typeattrs(), output);
  }

  // optional bytes valuesAttrs = 10;
  if (this->valuesattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      10, this->valuesattrs(), output);
  }

  // @@protoc_insertion_point(serialize_end:APSdet_GPB.AGP)
}

::google::protobuf::uint8* AGP::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:APSdet_GPB.AGP)
  // optional int32 numDimData = 1;
  if (this->numdimdata() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->numdimdata(), target);
  }

  // optional string dimData = 2;
  if (this->dimdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dimdata().data(), this->dimdata().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "APSdet_GPB.AGP.dimData");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->dimdata(), target);
  }

  // optional .APSdet_GPB.AGP.ArrayDataType dataType = 3;
  if (this->datatype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->datatype(), target);
  }

  // optional bytes valuesData = 4;
  if (this->valuesdata().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->valuesdata(), target);
  }

  // optional int32 unquieID = 5;
  if (this->unquieid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->unquieid(), target);
  }

  // optional double timeStamp = 6;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->timestamp(), target);
  }

  // optional int32 numAttrs = 7;
  if (this->numattrs() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->numattrs(), target);
  }

  // optional string nameAttrs = 8;
  if (this->nameattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nameattrs().data(), this->nameattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "APSdet_GPB.AGP.nameAttrs");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->nameattrs(), target);
  }

  // optional string typeAttrs = 9;
  if (this->typeattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->typeattrs().data(), this->typeattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "APSdet_GPB.AGP.typeAttrs");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->typeattrs(), target);
  }

  // optional bytes valuesAttrs = 10;
  if (this->valuesattrs().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        10, this->valuesattrs(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:APSdet_GPB.AGP)
  return target;
}

int AGP::ByteSize() const {
  int total_size = 0;

  // optional int32 numDimData = 1;
  if (this->numdimdata() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->numdimdata());
  }

  // optional string dimData = 2;
  if (this->dimdata().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->dimdata());
  }

  // optional .APSdet_GPB.AGP.ArrayDataType dataType = 3;
  if (this->datatype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->datatype());
  }

  // optional bytes valuesData = 4;
  if (this->valuesdata().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->valuesdata());
  }

  // optional int32 unquieID = 5;
  if (this->unquieid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->unquieid());
  }

  // optional double timeStamp = 6;
  if (this->timestamp() != 0) {
    total_size += 1 + 8;
  }

  // optional int32 numAttrs = 7;
  if (this->numattrs() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->numattrs());
  }

  // optional string nameAttrs = 8;
  if (this->nameattrs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nameattrs());
  }

  // optional string typeAttrs = 9;
  if (this->typeattrs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->typeattrs());
  }

  // optional bytes valuesAttrs = 10;
  if (this->valuesattrs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->valuesattrs());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AGP::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const AGP* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const AGP>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AGP::MergeFrom(const AGP& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.numdimdata() != 0) {
    set_numdimdata(from.numdimdata());
  }
  if (from.dimdata().size() > 0) {

    dimdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dimdata_);
  }
  if (from.datatype() != 0) {
    set_datatype(from.datatype());
  }
  if (from.valuesdata().size() > 0) {

    valuesdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.valuesdata_);
  }
  if (from.unquieid() != 0) {
    set_unquieid(from.unquieid());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.numattrs() != 0) {
    set_numattrs(from.numattrs());
  }
  if (from.nameattrs().size() > 0) {

    nameattrs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nameattrs_);
  }
  if (from.typeattrs().size() > 0) {

    typeattrs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.typeattrs_);
  }
  if (from.valuesattrs().size() > 0) {

    valuesattrs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.valuesattrs_);
  }
}

void AGP::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AGP::CopyFrom(const AGP& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AGP::IsInitialized() const {

  return true;
}

void AGP::Swap(AGP* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AGP::InternalSwap(AGP* other) {
  std::swap(numdimdata_, other->numdimdata_);
  dimdata_.Swap(&other->dimdata_);
  std::swap(datatype_, other->datatype_);
  valuesdata_.Swap(&other->valuesdata_);
  std::swap(unquieid_, other->unquieid_);
  std::swap(timestamp_, other->timestamp_);
  std::swap(numattrs_, other->numattrs_);
  nameattrs_.Swap(&other->nameattrs_);
  typeattrs_.Swap(&other->typeattrs_);
  valuesattrs_.Swap(&other->valuesattrs_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AGP::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AGP_descriptor_;
  metadata.reflection = AGP_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// AGP

// optional int32 numDimData = 1;
void AGP::clear_numdimdata() {
  numdimdata_ = 0;
}
 ::google::protobuf::int32 AGP::numdimdata() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.numDimData)
  return numdimdata_;
}
 void AGP::set_numdimdata(::google::protobuf::int32 value) {
  
  numdimdata_ = value;
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.numDimData)
}

// optional string dimData = 2;
void AGP::clear_dimdata() {
  dimdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& AGP::dimdata() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.dimData)
  return dimdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_dimdata(const ::std::string& value) {
  
  dimdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.dimData)
}
 void AGP::set_dimdata(const char* value) {
  
  dimdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:APSdet_GPB.AGP.dimData)
}
 void AGP::set_dimdata(const char* value, size_t size) {
  
  dimdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:APSdet_GPB.AGP.dimData)
}
 ::std::string* AGP::mutable_dimdata() {
  
  // @@protoc_insertion_point(field_mutable:APSdet_GPB.AGP.dimData)
  return dimdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AGP::release_dimdata() {
  
  return dimdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_allocated_dimdata(::std::string* dimdata) {
  if (dimdata != NULL) {
    
  } else {
    
  }
  dimdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dimdata);
  // @@protoc_insertion_point(field_set_allocated:APSdet_GPB.AGP.dimData)
}

// optional .APSdet_GPB.AGP.ArrayDataType dataType = 3;
void AGP::clear_datatype() {
  datatype_ = 0;
}
 ::APSdet_GPB::AGP_ArrayDataType AGP::datatype() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.dataType)
  return static_cast< ::APSdet_GPB::AGP_ArrayDataType >(datatype_);
}
 void AGP::set_datatype(::APSdet_GPB::AGP_ArrayDataType value) {
  
  datatype_ = value;
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.dataType)
}

// optional bytes valuesData = 4;
void AGP::clear_valuesdata() {
  valuesdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& AGP::valuesdata() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.valuesData)
  return valuesdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_valuesdata(const ::std::string& value) {
  
  valuesdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.valuesData)
}
 void AGP::set_valuesdata(const char* value) {
  
  valuesdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:APSdet_GPB.AGP.valuesData)
}
 void AGP::set_valuesdata(const void* value, size_t size) {
  
  valuesdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:APSdet_GPB.AGP.valuesData)
}
 ::std::string* AGP::mutable_valuesdata() {
  
  // @@protoc_insertion_point(field_mutable:APSdet_GPB.AGP.valuesData)
  return valuesdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AGP::release_valuesdata() {
  
  return valuesdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_allocated_valuesdata(::std::string* valuesdata) {
  if (valuesdata != NULL) {
    
  } else {
    
  }
  valuesdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valuesdata);
  // @@protoc_insertion_point(field_set_allocated:APSdet_GPB.AGP.valuesData)
}

// optional int32 unquieID = 5;
void AGP::clear_unquieid() {
  unquieid_ = 0;
}
 ::google::protobuf::int32 AGP::unquieid() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.unquieID)
  return unquieid_;
}
 void AGP::set_unquieid(::google::protobuf::int32 value) {
  
  unquieid_ = value;
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.unquieID)
}

// optional double timeStamp = 6;
void AGP::clear_timestamp() {
  timestamp_ = 0;
}
 double AGP::timestamp() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.timeStamp)
  return timestamp_;
}
 void AGP::set_timestamp(double value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.timeStamp)
}

// optional int32 numAttrs = 7;
void AGP::clear_numattrs() {
  numattrs_ = 0;
}
 ::google::protobuf::int32 AGP::numattrs() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.numAttrs)
  return numattrs_;
}
 void AGP::set_numattrs(::google::protobuf::int32 value) {
  
  numattrs_ = value;
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.numAttrs)
}

// optional string nameAttrs = 8;
void AGP::clear_nameattrs() {
  nameattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& AGP::nameattrs() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.nameAttrs)
  return nameattrs_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_nameattrs(const ::std::string& value) {
  
  nameattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.nameAttrs)
}
 void AGP::set_nameattrs(const char* value) {
  
  nameattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:APSdet_GPB.AGP.nameAttrs)
}
 void AGP::set_nameattrs(const char* value, size_t size) {
  
  nameattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:APSdet_GPB.AGP.nameAttrs)
}
 ::std::string* AGP::mutable_nameattrs() {
  
  // @@protoc_insertion_point(field_mutable:APSdet_GPB.AGP.nameAttrs)
  return nameattrs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AGP::release_nameattrs() {
  
  return nameattrs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_allocated_nameattrs(::std::string* nameattrs) {
  if (nameattrs != NULL) {
    
  } else {
    
  }
  nameattrs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nameattrs);
  // @@protoc_insertion_point(field_set_allocated:APSdet_GPB.AGP.nameAttrs)
}

// optional string typeAttrs = 9;
void AGP::clear_typeattrs() {
  typeattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& AGP::typeattrs() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.typeAttrs)
  return typeattrs_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_typeattrs(const ::std::string& value) {
  
  typeattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.typeAttrs)
}
 void AGP::set_typeattrs(const char* value) {
  
  typeattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:APSdet_GPB.AGP.typeAttrs)
}
 void AGP::set_typeattrs(const char* value, size_t size) {
  
  typeattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:APSdet_GPB.AGP.typeAttrs)
}
 ::std::string* AGP::mutable_typeattrs() {
  
  // @@protoc_insertion_point(field_mutable:APSdet_GPB.AGP.typeAttrs)
  return typeattrs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AGP::release_typeattrs() {
  
  return typeattrs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_allocated_typeattrs(::std::string* typeattrs) {
  if (typeattrs != NULL) {
    
  } else {
    
  }
  typeattrs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), typeattrs);
  // @@protoc_insertion_point(field_set_allocated:APSdet_GPB.AGP.typeAttrs)
}

// optional bytes valuesAttrs = 10;
void AGP::clear_valuesattrs() {
  valuesattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& AGP::valuesattrs() const {
  // @@protoc_insertion_point(field_get:APSdet_GPB.AGP.valuesAttrs)
  return valuesattrs_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_valuesattrs(const ::std::string& value) {
  
  valuesattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:APSdet_GPB.AGP.valuesAttrs)
}
 void AGP::set_valuesattrs(const char* value) {
  
  valuesattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:APSdet_GPB.AGP.valuesAttrs)
}
 void AGP::set_valuesattrs(const void* value, size_t size) {
  
  valuesattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:APSdet_GPB.AGP.valuesAttrs)
}
 ::std::string* AGP::mutable_valuesattrs() {
  
  // @@protoc_insertion_point(field_mutable:APSdet_GPB.AGP.valuesAttrs)
  return valuesattrs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* AGP::release_valuesattrs() {
  
  return valuesattrs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void AGP::set_allocated_valuesattrs(::std::string* valuesattrs) {
  if (valuesattrs != NULL) {
    
  } else {
    
  }
  valuesattrs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valuesattrs);
  // @@protoc_insertion_point(field_set_allocated:APSdet_GPB.AGP.valuesAttrs)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace APSdet_GPB

// @@protoc_insertion_point(global_scope)
