// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dataPipe.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dataPipe.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace detectorTest {

namespace {

const ::google::protobuf::Descriptor* MyMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MyMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_dataPipe_2eproto() {
  protobuf_AddDesc_dataPipe_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dataPipe.proto");
  GOOGLE_CHECK(file != NULL);
  MyMessage_descriptor_ = file->message_type(0);
  static const int MyMessage_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, numdimdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, dimdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, datatype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, valuesdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, numattrs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, nameattrs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, typeattrs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, valuesattrs_),
  };
  MyMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MyMessage_descriptor_,
      MyMessage::default_instance_,
      MyMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(MyMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MyMessage, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dataPipe_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MyMessage_descriptor_, &MyMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dataPipe_2eproto() {
  delete MyMessage::default_instance_;
  delete MyMessage_reflection_;
}

void protobuf_AddDesc_dataPipe_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016dataPipe.proto\022\014detectorTest\"\243\001\n\tMyMes"
    "sage\022\022\n\nnumDimData\030\001 \001(\005\022\017\n\007dimData\030\002 \001("
    "\t\022\020\n\010dataType\030\003 \001(\t\022\022\n\nvaluesData\030\004 \001(\014\022"
    "\020\n\010numAttrs\030\005 \001(\005\022\021\n\tnameAttrs\030\006 \001(\t\022\021\n\t"
    "typeAttrs\030\007 \001(\t\022\023\n\013valuesAttrs\030\010 \001(\014b\006pr"
    "oto3", 204);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dataPipe.proto", &protobuf_RegisterTypes);
  MyMessage::default_instance_ = new MyMessage();
  MyMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dataPipe_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dataPipe_2eproto {
  StaticDescriptorInitializer_dataPipe_2eproto() {
    protobuf_AddDesc_dataPipe_2eproto();
  }
} static_descriptor_initializer_dataPipe_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int MyMessage::kNumDimDataFieldNumber;
const int MyMessage::kDimDataFieldNumber;
const int MyMessage::kDataTypeFieldNumber;
const int MyMessage::kValuesDataFieldNumber;
const int MyMessage::kNumAttrsFieldNumber;
const int MyMessage::kNameAttrsFieldNumber;
const int MyMessage::kTypeAttrsFieldNumber;
const int MyMessage::kValuesAttrsFieldNumber;
#endif  // !_MSC_VER

MyMessage::MyMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:detectorTest.MyMessage)
}

void MyMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

MyMessage::MyMessage(const MyMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:detectorTest.MyMessage)
}

void MyMessage::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  numdimdata_ = 0;
  dimdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  datatype_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  numattrs_ = 0;
  nameattrs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  typeattrs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesattrs_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MyMessage::~MyMessage() {
  // @@protoc_insertion_point(destructor:detectorTest.MyMessage)
  SharedDtor();
}

void MyMessage::SharedDtor() {
  dimdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  datatype_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nameattrs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  typeattrs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesattrs_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void MyMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MyMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MyMessage_descriptor_;
}

const MyMessage& MyMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dataPipe_2eproto();
  return *default_instance_;
}

MyMessage* MyMessage::default_instance_ = NULL;

MyMessage* MyMessage::New(::google::protobuf::Arena* arena) const {
  MyMessage* n = new MyMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MyMessage::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MyMessage*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(numdimdata_, numattrs_);
  dimdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  datatype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  nameattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  typeattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuesattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool MyMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:detectorTest.MyMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 numDimData = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numdimdata_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_dimData;
        break;
      }

      // optional string dimData = 2;
      case 2: {
        if (tag == 18) {
         parse_dimData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dimdata()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->dimdata().data(), this->dimdata().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "detectorTest.MyMessage.dimData"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_dataType;
        break;
      }

      // optional string dataType = 3;
      case 3: {
        if (tag == 26) {
         parse_dataType:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_datatype()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->datatype().data(), this->datatype().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "detectorTest.MyMessage.dataType"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_valuesData;
        break;
      }

      // optional bytes valuesData = 4;
      case 4: {
        if (tag == 34) {
         parse_valuesData:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_valuesdata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_numAttrs;
        break;
      }

      // optional int32 numAttrs = 5;
      case 5: {
        if (tag == 40) {
         parse_numAttrs:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &numattrs_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_nameAttrs;
        break;
      }

      // optional string nameAttrs = 6;
      case 6: {
        if (tag == 50) {
         parse_nameAttrs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nameattrs()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nameattrs().data(), this->nameattrs().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "detectorTest.MyMessage.nameAttrs"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_typeAttrs;
        break;
      }

      // optional string typeAttrs = 7;
      case 7: {
        if (tag == 58) {
         parse_typeAttrs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_typeattrs()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->typeattrs().data(), this->typeattrs().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "detectorTest.MyMessage.typeAttrs"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_valuesAttrs;
        break;
      }

      // optional bytes valuesAttrs = 8;
      case 8: {
        if (tag == 66) {
         parse_valuesAttrs:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_valuesattrs()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:detectorTest.MyMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:detectorTest.MyMessage)
  return false;
#undef DO_
}

void MyMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:detectorTest.MyMessage)
  // optional int32 numDimData = 1;
  if (this->numdimdata() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->numdimdata(), output);
  }

  // optional string dimData = 2;
  if (this->dimdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dimdata().data(), this->dimdata().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.dimData");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->dimdata(), output);
  }

  // optional string dataType = 3;
  if (this->datatype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->datatype().data(), this->datatype().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.dataType");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->datatype(), output);
  }

  // optional bytes valuesData = 4;
  if (this->valuesdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->valuesdata(), output);
  }

  // optional int32 numAttrs = 5;
  if (this->numattrs() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->numattrs(), output);
  }

  // optional string nameAttrs = 6;
  if (this->nameattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nameattrs().data(), this->nameattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.nameAttrs");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->nameattrs(), output);
  }

  // optional string typeAttrs = 7;
  if (this->typeattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->typeattrs().data(), this->typeattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.typeAttrs");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->typeattrs(), output);
  }

  // optional bytes valuesAttrs = 8;
  if (this->valuesattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      8, this->valuesattrs(), output);
  }

  // @@protoc_insertion_point(serialize_end:detectorTest.MyMessage)
}

::google::protobuf::uint8* MyMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:detectorTest.MyMessage)
  // optional int32 numDimData = 1;
  if (this->numdimdata() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->numdimdata(), target);
  }

  // optional string dimData = 2;
  if (this->dimdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dimdata().data(), this->dimdata().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.dimData");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->dimdata(), target);
  }

  // optional string dataType = 3;
  if (this->datatype().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->datatype().data(), this->datatype().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.dataType");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->datatype(), target);
  }

  // optional bytes valuesData = 4;
  if (this->valuesdata().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->valuesdata(), target);
  }

  // optional int32 numAttrs = 5;
  if (this->numattrs() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->numattrs(), target);
  }

  // optional string nameAttrs = 6;
  if (this->nameattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nameattrs().data(), this->nameattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.nameAttrs");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->nameattrs(), target);
  }

  // optional string typeAttrs = 7;
  if (this->typeattrs().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->typeattrs().data(), this->typeattrs().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detectorTest.MyMessage.typeAttrs");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->typeattrs(), target);
  }

  // optional bytes valuesAttrs = 8;
  if (this->valuesattrs().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        8, this->valuesattrs(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:detectorTest.MyMessage)
  return target;
}

int MyMessage::ByteSize() const {
  int total_size = 0;

  // optional int32 numDimData = 1;
  if (this->numdimdata() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->numdimdata());
  }

  // optional string dimData = 2;
  if (this->dimdata().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->dimdata());
  }

  // optional string dataType = 3;
  if (this->datatype().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->datatype());
  }

  // optional bytes valuesData = 4;
  if (this->valuesdata().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->valuesdata());
  }

  // optional int32 numAttrs = 5;
  if (this->numattrs() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->numattrs());
  }

  // optional string nameAttrs = 6;
  if (this->nameattrs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nameattrs());
  }

  // optional string typeAttrs = 7;
  if (this->typeattrs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->typeattrs());
  }

  // optional bytes valuesAttrs = 8;
  if (this->valuesattrs().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->valuesattrs());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MyMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MyMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const MyMessage>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MyMessage::MergeFrom(const MyMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.numdimdata() != 0) {
    set_numdimdata(from.numdimdata());
  }
  if (from.dimdata().size() > 0) {

    dimdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dimdata_);
  }
  if (from.datatype().size() > 0) {

    datatype_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.datatype_);
  }
  if (from.valuesdata().size() > 0) {

    valuesdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.valuesdata_);
  }
  if (from.numattrs() != 0) {
    set_numattrs(from.numattrs());
  }
  if (from.nameattrs().size() > 0) {

    nameattrs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nameattrs_);
  }
  if (from.typeattrs().size() > 0) {

    typeattrs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.typeattrs_);
  }
  if (from.valuesattrs().size() > 0) {

    valuesattrs_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.valuesattrs_);
  }
}

void MyMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MyMessage::CopyFrom(const MyMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MyMessage::IsInitialized() const {

  return true;
}

void MyMessage::Swap(MyMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MyMessage::InternalSwap(MyMessage* other) {
  std::swap(numdimdata_, other->numdimdata_);
  dimdata_.Swap(&other->dimdata_);
  datatype_.Swap(&other->datatype_);
  valuesdata_.Swap(&other->valuesdata_);
  std::swap(numattrs_, other->numattrs_);
  nameattrs_.Swap(&other->nameattrs_);
  typeattrs_.Swap(&other->typeattrs_);
  valuesattrs_.Swap(&other->valuesattrs_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MyMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MyMessage_descriptor_;
  metadata.reflection = MyMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MyMessage

// optional int32 numDimData = 1;
void MyMessage::clear_numdimdata() {
  numdimdata_ = 0;
}
 ::google::protobuf::int32 MyMessage::numdimdata() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.numDimData)
  return numdimdata_;
}
 void MyMessage::set_numdimdata(::google::protobuf::int32 value) {
  
  numdimdata_ = value;
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.numDimData)
}

// optional string dimData = 2;
void MyMessage::clear_dimdata() {
  dimdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MyMessage::dimdata() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.dimData)
  return dimdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_dimdata(const ::std::string& value) {
  
  dimdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.dimData)
}
 void MyMessage::set_dimdata(const char* value) {
  
  dimdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:detectorTest.MyMessage.dimData)
}
 void MyMessage::set_dimdata(const char* value, size_t size) {
  
  dimdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:detectorTest.MyMessage.dimData)
}
 ::std::string* MyMessage::mutable_dimdata() {
  
  // @@protoc_insertion_point(field_mutable:detectorTest.MyMessage.dimData)
  return dimdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MyMessage::release_dimdata() {
  
  return dimdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_allocated_dimdata(::std::string* dimdata) {
  if (dimdata != NULL) {
    
  } else {
    
  }
  dimdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dimdata);
  // @@protoc_insertion_point(field_set_allocated:detectorTest.MyMessage.dimData)
}

// optional string dataType = 3;
void MyMessage::clear_datatype() {
  datatype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MyMessage::datatype() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.dataType)
  return datatype_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_datatype(const ::std::string& value) {
  
  datatype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.dataType)
}
 void MyMessage::set_datatype(const char* value) {
  
  datatype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:detectorTest.MyMessage.dataType)
}
 void MyMessage::set_datatype(const char* value, size_t size) {
  
  datatype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:detectorTest.MyMessage.dataType)
}
 ::std::string* MyMessage::mutable_datatype() {
  
  // @@protoc_insertion_point(field_mutable:detectorTest.MyMessage.dataType)
  return datatype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MyMessage::release_datatype() {
  
  return datatype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_allocated_datatype(::std::string* datatype) {
  if (datatype != NULL) {
    
  } else {
    
  }
  datatype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), datatype);
  // @@protoc_insertion_point(field_set_allocated:detectorTest.MyMessage.dataType)
}

// optional bytes valuesData = 4;
void MyMessage::clear_valuesdata() {
  valuesdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MyMessage::valuesdata() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.valuesData)
  return valuesdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_valuesdata(const ::std::string& value) {
  
  valuesdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.valuesData)
}
 void MyMessage::set_valuesdata(const char* value) {
  
  valuesdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:detectorTest.MyMessage.valuesData)
}
 void MyMessage::set_valuesdata(const void* value, size_t size) {
  
  valuesdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:detectorTest.MyMessage.valuesData)
}
 ::std::string* MyMessage::mutable_valuesdata() {
  
  // @@protoc_insertion_point(field_mutable:detectorTest.MyMessage.valuesData)
  return valuesdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MyMessage::release_valuesdata() {
  
  return valuesdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_allocated_valuesdata(::std::string* valuesdata) {
  if (valuesdata != NULL) {
    
  } else {
    
  }
  valuesdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valuesdata);
  // @@protoc_insertion_point(field_set_allocated:detectorTest.MyMessage.valuesData)
}

// optional int32 numAttrs = 5;
void MyMessage::clear_numattrs() {
  numattrs_ = 0;
}
 ::google::protobuf::int32 MyMessage::numattrs() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.numAttrs)
  return numattrs_;
}
 void MyMessage::set_numattrs(::google::protobuf::int32 value) {
  
  numattrs_ = value;
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.numAttrs)
}

// optional string nameAttrs = 6;
void MyMessage::clear_nameattrs() {
  nameattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MyMessage::nameattrs() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.nameAttrs)
  return nameattrs_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_nameattrs(const ::std::string& value) {
  
  nameattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.nameAttrs)
}
 void MyMessage::set_nameattrs(const char* value) {
  
  nameattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:detectorTest.MyMessage.nameAttrs)
}
 void MyMessage::set_nameattrs(const char* value, size_t size) {
  
  nameattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:detectorTest.MyMessage.nameAttrs)
}
 ::std::string* MyMessage::mutable_nameattrs() {
  
  // @@protoc_insertion_point(field_mutable:detectorTest.MyMessage.nameAttrs)
  return nameattrs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MyMessage::release_nameattrs() {
  
  return nameattrs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_allocated_nameattrs(::std::string* nameattrs) {
  if (nameattrs != NULL) {
    
  } else {
    
  }
  nameattrs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nameattrs);
  // @@protoc_insertion_point(field_set_allocated:detectorTest.MyMessage.nameAttrs)
}

// optional string typeAttrs = 7;
void MyMessage::clear_typeattrs() {
  typeattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MyMessage::typeattrs() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.typeAttrs)
  return typeattrs_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_typeattrs(const ::std::string& value) {
  
  typeattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.typeAttrs)
}
 void MyMessage::set_typeattrs(const char* value) {
  
  typeattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:detectorTest.MyMessage.typeAttrs)
}
 void MyMessage::set_typeattrs(const char* value, size_t size) {
  
  typeattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:detectorTest.MyMessage.typeAttrs)
}
 ::std::string* MyMessage::mutable_typeattrs() {
  
  // @@protoc_insertion_point(field_mutable:detectorTest.MyMessage.typeAttrs)
  return typeattrs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MyMessage::release_typeattrs() {
  
  return typeattrs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_allocated_typeattrs(::std::string* typeattrs) {
  if (typeattrs != NULL) {
    
  } else {
    
  }
  typeattrs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), typeattrs);
  // @@protoc_insertion_point(field_set_allocated:detectorTest.MyMessage.typeAttrs)
}

// optional bytes valuesAttrs = 8;
void MyMessage::clear_valuesattrs() {
  valuesattrs_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& MyMessage::valuesattrs() const {
  // @@protoc_insertion_point(field_get:detectorTest.MyMessage.valuesAttrs)
  return valuesattrs_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_valuesattrs(const ::std::string& value) {
  
  valuesattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:detectorTest.MyMessage.valuesAttrs)
}
 void MyMessage::set_valuesattrs(const char* value) {
  
  valuesattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:detectorTest.MyMessage.valuesAttrs)
}
 void MyMessage::set_valuesattrs(const void* value, size_t size) {
  
  valuesattrs_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:detectorTest.MyMessage.valuesAttrs)
}
 ::std::string* MyMessage::mutable_valuesattrs() {
  
  // @@protoc_insertion_point(field_mutable:detectorTest.MyMessage.valuesAttrs)
  return valuesattrs_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MyMessage::release_valuesattrs() {
  
  return valuesattrs_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MyMessage::set_allocated_valuesattrs(::std::string* valuesattrs) {
  if (valuesattrs != NULL) {
    
  } else {
    
  }
  valuesattrs_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valuesattrs);
  // @@protoc_insertion_point(field_set_allocated:detectorTest.MyMessage.valuesAttrs)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace detectorTest

// @@protoc_insertion_point(global_scope)
